# -*- coding: utf-8 -*-
"""Relocation of the National Southwestern Associated University.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ifsyil4HF_KhTOxWniveG-KTQSNtwggh
"""

import pandas as pd
import folium

# 1. 读取数据
# 假设你已经将 lianda_routes.csv 上传到了Colab
df = pd.read_csv('/content/Relocation of the National Southwestern Associated University.csv')

# 2. 创建底图，初始视角定位在中国中部
m = folium.Map(location=[27.0, 107.0], zoom_start=6)

# 3. 定义颜色方案，区分三条路线
colors = {1: 'blue', 2: 'green', 3: 'red'} # 海路用蓝，汽车用绿，步行用红

# 4. 分组绘制路线
for route_id, group in df.groupby('route_id'):
    group = group.sort_values('sequence') # 确保按顺序连接
    locations = group[['latitude', 'longitude']].values.tolist()
    route_name = group['route_name'].iloc[0]

    # 绘制连线
    folium.PolyLine(
        locations=locations,
        color=colors[route_id],
        weight=3,
        opacity=0.8,
        tooltip=route_name
    ).add_to(m)

    # 绘制点，并添加弹窗信息
    for idx, row in group.iterrows():
        folium.CircleMarker(
            location=[row['latitude'], row['longitude']],
            radius=6,
            color=colors[route_id],
            fill=True,
            popup=f"""
            <b>路线:</b> {row['route_name']}<br>
            <b>地点:</b> {row['location_name']}<br>
            <b>顺序:</b> {row['sequence']}<br>
            <b>描述:</b> {row['description']}
            """
        ).add_to(m)

# 5. 添加图例 (Folium本身不直接支持图例，需要HTML注入，这是一个简单方法)
legend_html = '''
     <div style="position: fixed;
                 top: 10px; left: 50px; width: 180px; height: 120px;
                 border:2px solid grey; z-index:9999; font-size:14px;
                 background-color:white">
     &nbsp;<strong>西南联大内迁路线</strong><br>
     &nbsp;<i class="fa fa-circle" style="color:blue"></i> 海陆并用路线<br>
     &nbsp;<i class="fa fa-circle" style="color:green"></i> 教授汽车团<br>
     &nbsp;<i class="fa fa-circle" style="color:red"></i> 湘黔滇步行团
     </div>
'''
m.get_root().html.add_child(folium.Element(legend_html))

# 6. 显示地图
m.save('lianda_route_map.html')
m